version: '3'

services:
  www:
    build: .
    ports:
      - '8001:80'
    volumes:
      - ./:/var/www/html/
    links:
      - db
    networks:
      - default
  #MySQL
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: avito-pro-intern-test
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - default
  #phpMyAdmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - '8000:80'
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - default
volumes:
    persistent: